default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: missionpossible_development
  username: <your_postgresql_username>
  password: <your_postgresql_password>
  host: localhost

test:
  <<: *default
  database: missionpossible_test
  username: <your_postgresql_username>
  password: <your_postgresql_password>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>