  default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: missionpossible_development
  username: your_postgresql_username
  password: your_postgresql_password
  host: localhost

test:
  <<: *default
  adapter: postgresql
  database: missionpossible_test
  username: your_postgresql_username
  password: your_postgresql_password
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>