default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: missionpossible_development
  username: admin
  password: 122333
  host: localhost

test:
  <<: *default
  database: missionpossible_test
  username: admin
  password: 122333
  host: localhost

production:
  <<: *default
  database: missionpossible_production_qrl1
  username: missionpossible_production_qrl1_user
  password: iMzFKRvSolptqzb6VVcMzL1op175XPRz
  host: dpg-cr6lsddds78s73bvr2rg-a
  port: 5432
